import { StyleSheet } from "react-native";

import { palette } from "./palette";

export const navigationAndMediaStyles = StyleSheet.create({
  bottomNav: {
    backgroundColor: "rgba(11,15,20,0.96)",
    flexDirection: "row",
    gap: 4,
    paddingHorizontal: 8,
    paddingTop: 8,
  },
  navItemButton: {
    alignItems: "center",
    borderRadius: 14,
    flex: 1,
    gap: 4,
    justifyContent: "center",
    paddingVertical: 8,
  },
  navItemButtonActive: {
    backgroundColor: palette.blueSoft,
  },
  navItemButtonPressed: {
    opacity: 0.7,
  },
  navItem: {
    alignItems: "center",
    flex: 1,
    gap: 4,
    justifyContent: "center",
  },
  navItemActive: {
  },
  navMarker: {
    backgroundColor: "transparent",
    borderRadius: 999,
    height: 3,
    width: 20,
  },
  navMarkerActive: {
    backgroundColor: palette.blue,
  },
  navLabel: {
    color: palette.subtle,
    fontSize: 11,
    fontWeight: "800",
  },
  navLabelActive: {
    color: palette.text,
  },
  sectionCard: {
    gap: 10,
    padding: 13,
  },
  courseGroup: {
    gap: 8,
  },
  courseList: {
    gap: 16,
  },
  plainList: {
    gap: 8,
  },
  courseListOuter: {
    gap: 20,
    paddingHorizontal: 0,
  },
  groupTitlePlain: {
    paddingHorizontal: 16,
    marginBottom: 0,
    fontSize: 14,
    fontWeight: "600",
    color: palette.muted,
  },
  courseListRowPlain: {
    alignItems: "center",
    flexDirection: "row",
    gap: 16,
    minHeight: 64,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: palette.border,
  },
  courseImagePreview: {
    width: 64,
    height: 48,
    borderRadius: 8,
    backgroundColor: palette.surfaceRaised,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  courseListRowContent: {
    flex: 1,
    justifyContent: "center",
    gap: 2,
  },
  courseListRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 12,
    minHeight: 64,
    paddingHorizontal: 13,
    paddingVertical: 11,
  },
  drilldownHeader: {
    alignItems: "center",
    flexDirection: "row",
    gap: 12,
  },
  backButton: {
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.04)",
    borderColor: "transparent",
    borderRadius: 9999,
    borderWidth: 0,
    height: 44,
    justifyContent: "center",
    width: 44,
  },
  groupTitle: {
    color: palette.subtle,
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 1.6,
    paddingHorizontal: 4,
    paddingTop: 4,
    textTransform: "uppercase",
  },
  moduleBlock: {
    gap: 10,
    padding: 12,
  },
  fileList: {
    gap: 8,
  },
  resourceGroup: {
    gap: 8,
  },
  resourceGroupTitle: {
    color: palette.muted,
    fontSize: 12,
    fontWeight: "800",
    lineHeight: 17,
  },
  sectionSummary: {
    color: palette.muted,
    fontSize: 13,
    lineHeight: 19,
  },
  courseSection: {
    gap: 8,
    marginTop: 16,
    marginBottom: 24,
  },
  courseSectionTitle: {
    color: palette.text,
    fontSize: 16,
    fontWeight: "700",
    marginBottom: 4,
  },
  courseHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    paddingVertical: 16,
    gap: 16,
  },
  courseHeaderContent: {
    flex: 1,
    gap: 4,
  },
  courseHeaderLabel: {
    color: palette.subtle,
    fontSize: 12,
    fontWeight: "700",
    textTransform: "uppercase",
  },
  courseHeaderTitle: {
    color: palette.text,
    fontSize: 24,
    fontWeight: "800",
    lineHeight: 30,
  },
  courseFileList: {
    gap: 8,
  },
  fileRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 10,
    minHeight: 52,
    paddingHorizontal: 10,
    paddingVertical: 9,
  },
  moduleRow: {
    alignItems: "flex-start",
    flexDirection: "row",
    gap: 10,
    paddingVertical: 3,
  },
  moduleRail: {
    backgroundColor: palette.blue,
    borderRadius: 999,
    height: 8,
    marginTop: 7,
    width: 8,
  },
  moduleLink: {
    color: palette.blue,
    fontSize: 12,
    lineHeight: 17,
  },
  modalSafeArea: {
    flex: 1,
    backgroundColor: palette.background,
    padding: 20,
    gap: 16,
  },
  modalHeader: {
    alignSelf: "center",
    gap: 14,
    maxWidth: 440,
    width: "100%",
  },
  modalTitle: {
    color: palette.text,
    fontSize: 27,
    fontWeight: "800",
  },
  modalBody: {
    color: palette.muted,
    fontSize: 14,
    lineHeight: 22,
  },
  modalCameraFrame: {
    backgroundColor: "#000",
    borderColor: palette.borderStrong,
    borderRadius: 14,
    borderWidth: 1,
    flex: 1,
    maxHeight: 500,
    maxWidth: 440,
    minHeight: 280,
    width: "100%",
    alignSelf: "center",
    overflow: "hidden",
    position: "relative",
  },
  camera: {
    flex: 1,
  },
  scanGuide: {
    aspectRatio: 1,
    borderColor: "rgba(248,250,252,0.9)",
    borderRadius: 14,
    borderWidth: 2,
    left: "15%",
    position: "absolute",
    top: "24%",
    width: "70%",
  },
  webScannerShell: {
    alignSelf: "stretch",
    flex: 1,
    gap: 12,
    minHeight: 0,
    width: "100%",
  },
  webCameraPicker: {
    gap: 6,
    width: "100%",
  },
  webCameraToolbar: {
    alignItems: "center",
    flexDirection: "row",
    gap: 10,
    width: "100%",
  },
  webCameraPill: {
    backgroundColor: "#121820",
    borderColor: palette.borderStrong,
    borderRadius: 14,
    borderWidth: 1,
    flex: 1,
    justifyContent: "center",
    minHeight: 56,
    paddingHorizontal: 18,
  },
  webCameraLabel: {
    color: palette.text,
    fontSize: 16,
    fontWeight: "700",
  },
  webCameraSwitch: {
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.08)",
    borderRadius: 9999,
    justifyContent: "center",
    minHeight: 44,
    paddingHorizontal: 16,
  },
  webCameraSwitchText: {
    color: palette.text,
    fontSize: 13,
    fontWeight: "800",
  },
  webVideoFrame: {
    backgroundColor: "#000",
    borderColor: palette.borderStrong,
    borderRadius: 14,
    borderWidth: 1,
    flex: 1,
    minHeight: 0,
    overflow: "hidden",
    position: "relative",
    width: "100%",
  },
  permissionBox: {
    alignItems: "center",
    backgroundColor: palette.surface,
    borderColor: palette.border,
    borderRadius: 14,
    borderWidth: 1,
    flex: 1,
    justifyContent: "center",
    padding: 20,
  },
  permissionText: {
    color: palette.text,
    fontSize: 14,
    lineHeight: 22,
    textAlign: "center",
  },
  iconButton: {
    alignItems: "center",
    borderColor: "transparent",
    borderRadius: 9999,
    borderWidth: 0,
    height: 44,
    justifyContent: "center",
    width: 44,
  },
  pdfModal: {
    backgroundColor: palette.background,
    flex: 1,
  },
  pdfHeader: {
    alignItems: "center",
    borderBottomColor: palette.border,
    borderBottomWidth: 1,
    flexDirection: "row",
    gap: 12,
    paddingBottom: 12,
    paddingHorizontal: 16,
    paddingTop: 54,
  },
  pdfTitle: {
    color: palette.text,
    fontSize: 16,
    fontWeight: "800",
  },
  pdfFrame: {
    flex: 1,
  },
  pdfWebView: {
    backgroundColor: palette.background,
    flex: 1,
  },
});
