import { StyleSheet } from "react-native";

import { palette } from "./palette";

export const formAndOverlayStyles = StyleSheet.create({
  input: {
    backgroundColor: "rgba(255,255,255,0.06)",
    borderColor: "transparent",
    borderRadius: 9999,
    borderWidth: 0,
    color: palette.text,
    fontSize: 16,
    minHeight: 56,
    paddingHorizontal: 24,
    paddingVertical: 12,
  },
  searchRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 8,
    backgroundColor: "rgba(255,255,255,0.06)",
    borderRadius: 9999,
    minHeight: 56,
    paddingHorizontal: 24,
  },
  searchInput: {
    backgroundColor: "transparent",
    borderWidth: 0,
    color: palette.text,
    fontSize: 16,
    flex: 1,
    minHeight: 46,
    paddingHorizontal: 0,
  },
  emptyText: {
    color: palette.muted,
    fontSize: 14,
    lineHeight: 22,
  },
  loadingPanel: {
    alignItems: "center",
    minHeight: 96,
    justifyContent: "center",
  },
  statusBanner: {
    gap: 8,
    padding: 14,
  },
  statusBannerHeaderRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 12,
    justifyContent: "space-between",
  },
  statusBannerTitleRow: {
    alignItems: "center",
    flexDirection: "row",
    flex: 1,
    gap: 10,
    minWidth: 0,
  },
  statusBannerDismissButton: {
    alignItems: "center",
    borderRadius: 9999,
    borderWidth: 0,
    height: 32,
    justifyContent: "center",
    width: 32,
  },
  floatingBannerContainer: {
    position: 'absolute',
    bottom: 24,
    left: 16,
    right: 16,
    zIndex: 9999,
  },
  floatingBannerContainerWithBottomNav: {
    bottom: 92,
  },
  floatingBannerCard: {
    ...({
        boxShadow: "0px 10px 40px -10px rgba(0,0,0,0.6)",
    } as object),
    borderRadius: 22,
    borderWidth: 0,
    backgroundColor: "rgba(16,23,34,0.98)",
  },
  floatingBannerCardError: {
    backgroundColor: "rgba(35,17,24,0.98)",
  },
  statusBannerInfo: {
  },
  statusBannerError: {
  },
  statusTitle: {
    color: palette.text,
    fontSize: 14,
    fontWeight: "800",
  },
  statusBody: {
    color: "rgba(248,250,252,0.8)",
    fontSize: 13,
    lineHeight: 19,
  },
  errorText: {
    color: "#fecdd3",
    fontSize: 13,
    lineHeight: 19,
  },
  codexHeaderRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 12,
  },
  codexRoot: {
    flex: 1,
    overflow: "hidden",
    paddingHorizontal: 20,
    position: "relative",
  },
  codexChatScroll: {
    flex: 1,
  },
  codexChatContent: {
    gap: 18,
    paddingTop: 8,
    paddingBottom: 116,
  },
  codexStatusBar: {
    alignItems: "flex-start",
    backgroundColor: "transparent",
    borderRadius: 0,
    flexDirection: "column",
    gap: 12,
    paddingVertical: 8,
  },
  codexStatusTitle: {
    color: palette.text,
    fontSize: 16,
    fontWeight: "900",
    lineHeight: 21,
  },
  codexStatusBody: {
    color: palette.muted,
    fontSize: 13,
    lineHeight: 19,
  },
  codexAuthButton: {
    alignItems: "center",
    alignSelf: "flex-start",
    backgroundColor: palette.text,
    borderRadius: 9999,
    flexDirection: "row",
    gap: 8,
    minHeight: 42,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  codexAuthButtonReady: {
    backgroundColor: palette.greenSoft,
  },
  codexAuthButtonText: {
    color: palette.ink,
    fontSize: 14,
    fontWeight: "900",
  },
  codexAuthButtonTextReady: {
    color: palette.green,
  },
  codexAuthCard: {
    backgroundColor: "rgba(255,255,255,0.06)",
    borderRadius: 26,
    gap: 12,
    padding: 18,
  },
  codexAuthCardTitle: {
    color: palette.text,
    fontSize: 18,
    fontWeight: "900",
    lineHeight: 24,
  },
  codexAuthCardBody: {
    color: palette.muted,
    fontSize: 14,
    lineHeight: 21,
  },
  codexDeviceCode: {
    alignSelf: "flex-start",
    backgroundColor: "rgba(0,0,0,0.22)",
    borderRadius: 9999,
    color: palette.text,
    fontSize: 22,
    fontWeight: "900",
    letterSpacing: 1.2,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  codexAuthLinkButton: {
    alignItems: "center",
    alignSelf: "flex-start",
    backgroundColor: palette.blueSoft,
    borderRadius: 9999,
    minHeight: 40,
    paddingHorizontal: 16,
    paddingVertical: 9,
  },
  codexAuthLinkButtonText: {
    color: palette.blue,
    fontSize: 14,
    fontWeight: "900",
  },
  codexIcon: {
    alignItems: "center",
    backgroundColor: palette.blueSoft,
    borderRadius: 9999,
    height: 44,
    justifyContent: "center",
    width: 44,
  },
  codexIconText: {
    color: palette.blue,
  },
  codexToolStrip: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  codexToolChip: {
    backgroundColor: "rgba(125,211,166,0.12)",
    borderRadius: 9999,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  codexToolChipText: {
    color: palette.green,
    fontSize: 12,
    fontWeight: "800",
  },
  codexUserBubble: {
    alignSelf: "flex-end",
    backgroundColor: "rgba(255,255,255,0.11)",
    borderRadius: 28,
    maxWidth: "82%",
    paddingHorizontal: 18,
    paddingVertical: 14,
  },
  codexUserBubbleText: {
    color: palette.text,
    fontSize: 18,
    lineHeight: 25,
  },
  chatMessageRow: {
    width: "100%",
  },
  codexAssistantRow: {
    flexDirection: "row",
    gap: 12,
    marginTop: 8,
    width: "100%",
  },
  codexAssistantAvatar: {
    alignItems: "center",
    backgroundColor: "rgba(140,199,255,0.08)",
    borderRadius: 9999,
    height: 32,
    justifyContent: "center",
    marginTop: 4,
    width: 32,
  },
  codexAssistantContent: {
    flex: 1,
    gap: 8,
  },
  codexAssistantBubble: {
    gap: 4,
    paddingVertical: 4,
  },
  codexAssistantBubbleEmpty: {
    gap: 4,
    paddingVertical: 4,
  },
  codexResponseTextMuted: {
    color: "rgba(248,250,252,0.4)",
    fontSize: 20,
    lineHeight: 31,
  },
  codexErrorBubble: {
    backgroundColor: "rgba(244,63,94,0.12)",
    borderRadius: 16,
    padding: 16,
  },
  codexErrorText: {
    color: palette.red,
    fontSize: 16,
    lineHeight: 24,
  },
  codexScrollPadding: {
    height: 32,
  },
  codexTranscript: {
    backgroundColor: palette.surface,
    borderRadius: 24,
    gap: 12,
    padding: 16,
  },
  codexEmptyTranscript: {
    backgroundColor: "rgba(255,255,255,0.04)",
    borderRadius: 24,
    gap: 10,
    minHeight: 180,
    justifyContent: "center",
    padding: 18,
  },
  codexTranscriptPlain: {
    gap: 14,
  },
  codexEmptyTranscriptPlain: {
    gap: 16,
    justifyContent: "center",
    minHeight: 180,
  },
  codexEmptyTitle: {
    color: palette.text,
    fontSize: 24,
    fontWeight: "900",
    lineHeight: 31,
  },
  codexEmptyBody: {
    color: "rgba(248,250,252,0.84)",
    fontSize: 18,
    lineHeight: 28,
  },
  codexResponseText: {
    color: "rgba(248,250,252,0.92)",
    fontSize: 20,
    lineHeight: 31,
  },
  codexComposerDock: {
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.06)",
    borderRadius: 32,
    bottom: 24,
    flexDirection: "row",
    gap: 12,
    left: 20,
    paddingLeft: 20,
    paddingRight: 8,
    paddingVertical: 8,
    position: "absolute",
    right: 20,
  },
  codexComposerDockWeb: {
    bottom: 82,
    zIndex: 50,
    ...({
      position: "fixed",
    } as object),
  },
  codexPromptInput: {
    backgroundColor: "transparent",
    borderRadius: 0,
    flex: 1,
    height: 56,
    maxHeight: 56,
    minHeight: 56,
    paddingHorizontal: 0,
    paddingVertical: 0,
    color: palette.text,
    fontSize: 20,
    lineHeight: 28,
  },
  codexComposerActions: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "flex-end",
  },
  codexSendButton: {
    alignItems: "center",
    backgroundColor: palette.text,
    borderRadius: 9999,
    height: 52,
    justifyContent: "center",
    width: 52,
  },
  codexSendButtonWeb: {},
  statusDebugText: {
    color: "rgba(254,205,211,0.82)",
    fontSize: 12,
    lineHeight: 18,
  },
});
