import { StyleSheet } from "react-native";

export const palette = {
  background: "#0b0f14",
  backgroundElevated: "#101722",
  surface: "#121820",
  surfaceRaised: "#18202a",
  border: "rgba(255,255,255,0.09)",
  borderStrong: "rgba(255,255,255,0.18)",
  text: "#f8fafc",
  muted: "#a8b3c1",
  subtle: "#738091",
  green: "#7dd3a6",
  greenSoft: "rgba(45,212,132,0.13)",
  blue: "#8cc7ff",
  blueSoft: "rgba(56,189,248,0.13)",
  amber: "#f7c873",
  amberSoft: "rgba(245,158,11,0.13)",
  red: "#fda4af",
  redSoft: "rgba(244,63,94,0.14)",
  ink: "#071018",
};

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: palette.background,
  },
  surfaceFrame: {
    backgroundColor: palette.surface,
    borderRadius: 24,
    overflow: "hidden",
  },
  surfaceFrameRaised: {
    backgroundColor: palette.surfaceRaised,
  },
  surfaceFrameReady: {
    backgroundColor: "rgba(140,199,255,0.06)",
  },
  heroSurface: {
    backgroundColor: "#101720",
  },
  appShell: {
    flex: 1,
  },
  mainScroll: {
    flex: 1,
  },
  topBar: {
    paddingHorizontal: 20,
    paddingTop: 14,
    paddingBottom: 10,
  },
  brandRow: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 12,
  },
  brandCopy: {
    flex: 1,
    gap: 4,
  },
  eyebrow: {
    color: palette.subtle,
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 2.6,
    textTransform: "uppercase",
  },
  brandLabel: {
    color: palette.subtle,
    fontSize: 13,
    fontWeight: "700",
  },
  appTitle: {
    color: palette.text,
    fontSize: 24,
    fontWeight: "800",
  },
  appSubtitle: {
    color: palette.muted,
    fontSize: 14,
    lineHeight: 21,
    marginTop: 8,
  },
  connectionPill: {
    alignItems: "center",
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: "row",
    gap: 7,
    paddingHorizontal: 11,
    paddingVertical: 8,
  },
  connectionPillReady: {
    backgroundColor: palette.greenSoft,
    borderColor: "rgba(125,211,166,0.35)",
  },
  connectionPillWaiting: {
    backgroundColor: palette.amberSoft,
    borderColor: "rgba(247,200,115,0.35)",
  },
  pillDot: {
    borderRadius: 999,
    height: 8,
    width: 8,
  },
  pillDotReady: {
    backgroundColor: palette.green,
  },
  pillDotWaiting: {
    backgroundColor: palette.amber,
  },
  connectionPillText: {
    color: palette.text,
    fontSize: 12,
    fontWeight: "800",
  },
  scrollContent: { flexGrow: 1,
    gap: 14,
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 24,
  },
  screen: { flex: 1,
    gap: 14,
  },
  connectStage: {
    flex: 1,
    marginHorizontal: -20,
    marginTop: -8,
    overflow: "hidden",
    paddingHorizontal: 0,
    paddingTop: 0,
    paddingBottom: 0,
    position: "relative",
  },
  connectStageBackgroundImage: {
    bottom: 0,
    height: "100%",
    left: 0,
    right: 0,
    top: 0,
    width: "100%",
    ...({
      objectFit: "cover",
      objectPosition: "50% 50%",
    } as object),
  },
  connectStageSideGradientLeft: {
    bottom: 0,
    left: 0,
    position: "absolute",
    top: 0,
    width: "24%",
    zIndex: 1,
    ...({
      backgroundImage:
        "linear-gradient(90deg, rgba(0,0,0,0.82), rgba(0,0,0,0))",
    } as object),
  },
  connectStageSideGradientRight: {
    bottom: 0,
    position: "absolute",
    right: 0,
    top: 0,
    width: "24%",
    zIndex: 1,
    ...({
      backgroundImage:
        "linear-gradient(270deg, rgba(0,0,0,0.82), rgba(0,0,0,0))",
    } as object),
  },
  connectStageBottomGradient: {
    bottom: 0,
    height: "38%",
    left: 0,
    position: "absolute",
    right: 0,
    zIndex: 1,
    ...({
      backgroundImage:
        "linear-gradient(0deg, rgba(0,0,0,0.58), rgba(0,0,0,0))",
    } as object),
  },
  connectHelpSection: {
    gap: 12,
    paddingTop: 8,
  },
  qrImportMenu: {
    gap: 12,
  },
  qrImportMenuContent: {
    gap: 12,
  },
  qrImportHeader: {
    gap: 4,
  },
  qrImportHint: {
    color: palette.subtle,
    fontSize: 12,
    lineHeight: 18,
  },
  qrImportSupport: {
    paddingTop: 4,
  },
  connectStageContent: {
    flex: 1,
    justifyContent: "space-between",
    position: "relative",
    width: "100%",
    zIndex: 2,
  },
  connectSection: {
    gap: 14,
    paddingBottom: 18,
    paddingTop: 4,
  },
  connectWelcomeHero: {
    alignItems: "center",
    flex: 1,
    justifyContent: "center",
    paddingHorizontal: 24,
    paddingTop: 96,
    paddingBottom: 24,
  },
  connectWelcomeCopy: {
    alignItems: "center",
    gap: 14,
    maxWidth: 620,
    marginTop: 18,
  },
  connectWelcomeLogoHalo: {
    display: "none",
  },
  connectWelcomeLogo: {
    height: 240,
    width: 240,
  },
  connectWelcomeTitle: {
    color: palette.text,
    fontSize: 34,
    fontWeight: "900",
    letterSpacing: -0.6,
    lineHeight: 40,
    textAlign: "center",
  },
  connectWelcomeBody: {
    color: "rgba(248,250,252,0.78)",
    fontSize: 17,
    fontWeight: "600",
    lineHeight: 30,
    maxWidth: 560,
    textAlign: "center",
  },
  connectWelcomeActions: {
    alignItems: "center",
    backgroundColor: "transparent",
    gap: 12,
    paddingHorizontal: 24,
    paddingTop: 56,
    paddingBottom: 36,
    width: "100%",
  },
  connectWelcomePrimaryButton: {
    alignSelf: "stretch",
    borderRadius: 9999,
    minHeight: 56,
    paddingHorizontal: 24,
    width: "100%",
  },
  connectWelcomePrimaryButtonText: {
    fontSize: 17,
    fontWeight: "800",
    letterSpacing: -0.2,
  },
  ghostButton: {
    alignItems: "center",
    alignSelf: "center",
    backgroundColor: "transparent",
    borderColor: "transparent",
    borderRadius: 9999,
    borderWidth: 0,
    flexDirection: "row",
    flexWrap: "nowrap",
    gap: 10,
    justifyContent: "center",
    minHeight: 44,
    paddingHorizontal: 16,
    paddingVertical: 8,
  },
  ghostButtonText: {
    color: palette.text,
    fontSize: 16,
    fontWeight: "700",
  },
  connectWelcomeSecondaryAction: {
    alignSelf: "center",
    opacity: 0.88,
    paddingHorizontal: 12,
  },
  connectWelcomeSecondaryActionText: {
    color: "rgba(248,250,252,0.86)",
    fontSize: 16,
    fontWeight: "700",
  },
  infoPanel: {
    gap: 10,
    padding: 13,
  },
  heroPanel: {
    gap: 18,
    padding: 22,
  },
  heroPanelReady: {
  },
  heroLabel: {
    color: palette.subtle,
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 2.2,
    textTransform: "uppercase",
  },
  heroTitle: {
    color: palette.text,
    fontSize: 21,
    fontWeight: "800",
    lineHeight: 27,
  },
  heroBody: {
    color: palette.muted,
    fontSize: 14,
    lineHeight: 22,
  },
  card: {
    gap: 12,
    padding: 16,
  },
  cardCompact: {
    padding: 10,
  },
  cardRaised: {
  },
  cardTitle: {
    color: palette.text,
    fontSize: 16,
    fontWeight: "800",
    lineHeight: 21,
  },
  cardBody: {
    color: palette.muted,
    fontSize: 14,
    lineHeight: 22,
  },
  tipList: {
    gap: 8,
  },
  tipItem: {
    color: palette.muted,
    fontSize: 14,
    lineHeight: 22,
  },
  tipItemStrong: {
    color: palette.text,
    fontWeight: "800",
  },
  sectionHeader: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 12,
    paddingTop: 4,
  },
  sectionTitle: {
    color: palette.text,
    fontSize: 17,
    fontWeight: "800",
  },
  sectionKicker: {
    color: palette.subtle,
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 2,
    textTransform: "uppercase",
  },
  actionRow: {
    alignItems: "stretch",
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  buttonBase: {
    alignItems: "center",
    borderRadius: 9999,
    borderWidth: 0,
    flexDirection: "row",
    flexWrap: "nowrap",
    justifyContent: "center",
    gap: 8,
    minHeight: 56,
    paddingHorizontal: 24,
  },
  buttonFill: {
    width: "100%",
  },
  primaryButton: {
    backgroundColor: palette.text,
  },
  primaryButtonText: {
    color: palette.ink,
    fontSize: 16,
    fontWeight: "800",
  },
  secondaryButton: {
    backgroundColor: "rgba(255,255,255,0.06)",
  },
  secondaryButtonText: {
    color: palette.text,
    fontSize: 16,
    fontWeight: "800",
  },
  buttonDisabled: {
    opacity: 0.56,
  },
  pressed: {
    opacity: 0.78,
    transform: [{ scale: 0.99 }],
  },
  metricGrid: {
    flexDirection: "row",
    gap: 10,
  },
  metricCard: {
    flex: 1,
    gap: 7,
    minHeight: 86,
    padding: 14,
  },
  metricLabel: {
    color: palette.subtle,
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 1.8,
    textTransform: "uppercase",
  },
  metricValue: {
    color: palette.text,
    fontSize: 21,
    fontWeight: "800",
  },
  metricHint: {
    color: palette.muted,
    fontSize: 12,
    lineHeight: 17,
  },
  listRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 12,
    padding: 12,
  },
  listRowActive: {
  },
  courseAvatar: {
    alignItems: "center",
    backgroundColor: "#223041",
    borderRadius: 14,
    height: 42,
    justifyContent: "center",
    width: 42,
  },
  courseAvatarText: {
    color: palette.blue,
    fontSize: 13,
    fontWeight: "900",
  },
  rowText: {
    flex: 1,
    gap: 3,
  },
  rowTitle: {
    color: palette.text,
    fontSize: 14,
    fontWeight: "800",
    lineHeight: 19,
  },
  rowSubtitle: {
    color: palette.muted,
    fontSize: 12,
    lineHeight: 17,
  },
  badge: {
    alignSelf: "flex-start",
    borderColor: palette.borderStrong,
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 9,
    paddingVertical: 5,
  },
  badgeText: {
    color: palette.muted,
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 1.2,
    textTransform: "uppercase",
  },
  input: {
    backgroundColor: "rgba(255,255,255,0.06)",
    borderColor: "transparent",
    borderRadius: 9999,
    borderWidth: 0,
    color: palette.text,
    fontSize: 16,
    minHeight: 56,
    paddingHorizontal: 24,
    paddingVertical: 12,
  },
  searchRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 8,
    backgroundColor: "rgba(255,255,255,0.06)",
    borderRadius: 9999,
    minHeight: 56,
    paddingHorizontal: 24,
  },
  searchInput: {
    backgroundColor: "transparent",
    borderWidth: 0,
    color: palette.text,
    fontSize: 16,
    flex: 1,
    minHeight: 46,
    paddingHorizontal: 0,
  },
  emptyText: {
    color: palette.muted,
    fontSize: 14,
    lineHeight: 22,
  },
  loadingPanel: {
    alignItems: "center",
    minHeight: 96,
    justifyContent: "center",
  },
  statusBanner: {
    gap: 8,
    padding: 14,
  },
  statusBannerHeaderRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 12,
    justifyContent: "space-between",
  },
  statusBannerTitleRow: {
    alignItems: "center",
    flexDirection: "row",
    flex: 1,
    gap: 10,
    minWidth: 0,
  },
  statusBannerDismissButton: {
    alignItems: "center",
    borderRadius: 9999,
    borderWidth: 0,
    height: 32,
    justifyContent: "center",
    width: 32,
  },
  floatingBannerContainer: {
    position: 'absolute',
    bottom: 24,
    left: 16,
    right: 16,
    zIndex: 9999,
  },
  floatingBannerContainerWithBottomNav: {
    bottom: 92,
  },
  floatingBannerCard: {
    ...({
        boxShadow: "0px 10px 40px -10px rgba(0,0,0,0.6)",
    } as object),
    borderRadius: 22,
    borderWidth: 0,
    backgroundColor: "rgba(16,23,34,0.98)",
  },
  floatingBannerCardError: {
    backgroundColor: "rgba(35,17,24,0.98)",
  },
  statusBannerInfo: {
  },
  statusBannerError: {
  },
  statusTitle: {
    color: palette.text,
    fontSize: 14,
    fontWeight: "800",
  },
  statusBody: {
    color: "rgba(248,250,252,0.8)",
    fontSize: 13,
    lineHeight: 19,
  },
  errorText: {
    color: "#fecdd3",
    fontSize: 13,
    lineHeight: 19,
  },
  statusDebugText: {
    color: "rgba(254,205,211,0.82)",
    fontSize: 12,
    lineHeight: 18,
  },
  bottomNav: {
    backgroundColor: "rgba(11,15,20,0.96)",
    flexDirection: "row",
    gap: 8,
    paddingBottom: 18,
    paddingHorizontal: 12,
    paddingTop: 10,
  },
  navItem: {
    alignItems: "center",
    flex: 1,
    gap: 4,
    minHeight: 54,
    justifyContent: "center",
  },
  navItemActive: {
  },
  navMarker: {
    backgroundColor: "transparent",
    borderRadius: 999,
    height: 3,
    width: 20,
  },
  navMarkerActive: {
    backgroundColor: palette.blue,
  },
  navLabel: {
    color: palette.subtle,
    fontSize: 11,
    fontWeight: "800",
  },
  navLabelActive: {
    color: palette.text,
  },
  sectionCard: {
    gap: 10,
    padding: 13,
  },
  courseGroup: {
    gap: 8,
  },
  courseList: {
    gap: 16,
  },
  plainList: {
    gap: 8,
  },
  courseListOuter: {
    gap: 20,
    paddingHorizontal: 0,
  },
  groupTitlePlain: {
    paddingHorizontal: 16,
    marginBottom: 0,
    fontSize: 14,
    fontWeight: "600",
    color: palette.muted,
  },
  courseListRowPlain: {
    alignItems: "center",
    flexDirection: "row",
    gap: 16,
    minHeight: 64,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: palette.border,
  },
  courseImagePreview: {
    width: 64,
    height: 48,
    borderRadius: 8,
    backgroundColor: palette.surfaceRaised,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  courseListRowContent: {
    flex: 1,
    justifyContent: "center",
    gap: 2,
  },
  courseListRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 12,
    minHeight: 64,
    paddingHorizontal: 13,
    paddingVertical: 11,
  },
  drilldownHeader: {
    alignItems: "center",
    flexDirection: "row",
    gap: 12,
  },
  backButton: {
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.04)",
    borderColor: "transparent",
    borderRadius: 9999,
    borderWidth: 0,
    height: 44,
    justifyContent: "center",
    width: 44,
  },
  groupTitle: {
    color: palette.subtle,
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 1.6,
    paddingHorizontal: 4,
    paddingTop: 4,
    textTransform: "uppercase",
  },
  moduleBlock: {
    gap: 10,
    padding: 12,
  },
  fileList: {
    gap: 8,
  },
  resourceGroup: {
    gap: 8,
  },
  resourceGroupTitle: {
    color: palette.muted,
    fontSize: 12,
    fontWeight: "800",
    lineHeight: 17,
  },
  sectionSummary: {
    color: palette.muted,
    fontSize: 13,
    lineHeight: 19,
  },
  courseSection: {
    gap: 8,
    marginTop: 16,
    marginBottom: 24,
  },
  courseSectionTitle: {
    color: palette.text,
    fontSize: 16,
    fontWeight: "700",
    marginBottom: 4,
  },
  courseHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    paddingVertical: 16,
    gap: 16,
  },
  courseHeaderContent: {
    flex: 1,
    gap: 4,
  },
  courseHeaderLabel: {
    color: palette.subtle,
    fontSize: 12,
    fontWeight: "700",
    textTransform: "uppercase",
  },
  courseHeaderTitle: {
    color: palette.text,
    fontSize: 24,
    fontWeight: "800",
    lineHeight: 30,
  },
  courseFileList: {
    gap: 8,
  },
  fileRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 10,
    minHeight: 52,
    paddingHorizontal: 10,
    paddingVertical: 9,
  },
  moduleRow: {
    alignItems: "flex-start",
    flexDirection: "row",
    gap: 10,
    paddingVertical: 3,
  },
  moduleRail: {
    backgroundColor: palette.blue,
    borderRadius: 999,
    height: 8,
    marginTop: 7,
    width: 8,
  },
  moduleLink: {
    color: palette.blue,
    fontSize: 12,
    lineHeight: 17,
  },
  modalSafeArea: {
    flex: 1,
    backgroundColor: palette.background,
    padding: 20,
    gap: 16,
  },
  modalHeader: {
    alignSelf: "center",
    gap: 14,
    maxWidth: 440,
    width: "100%",
  },
  modalTitle: {
    color: palette.text,
    fontSize: 27,
    fontWeight: "800",
  },
  modalBody: {
    color: palette.muted,
    fontSize: 14,
    lineHeight: 22,
  },
  modalCameraFrame: {
    backgroundColor: "#000",
    borderColor: palette.borderStrong,
    borderRadius: 14,
    borderWidth: 1,
    flex: 1,
    maxHeight: 500,
    maxWidth: 440,
    minHeight: 280,
    width: "100%",
    alignSelf: "center",
    overflow: "hidden",
    position: "relative",
  },
  camera: {
    flex: 1,
  },
  scanGuide: {
    aspectRatio: 1,
    borderColor: "rgba(248,250,252,0.9)",
    borderRadius: 14,
    borderWidth: 2,
    left: "15%",
    position: "absolute",
    top: "24%",
    width: "70%",
  },
  webScannerShell: {
    alignSelf: "center",
    flex: 1,
    gap: 12,
    maxHeight: 500,
    maxWidth: 440,
    minHeight: 340,
    width: "100%",
  },
  webCameraPicker: {
    gap: 6,
  },
  webVideoFrame: {
    backgroundColor: "#000",
    borderColor: palette.borderStrong,
    borderRadius: 14,
    borderWidth: 1,
    flex: 1,
    minHeight: 280,
    overflow: "hidden",
    position: "relative",
  },
  permissionBox: {
    alignItems: "center",
    backgroundColor: palette.surface,
    borderColor: palette.border,
    borderRadius: 14,
    borderWidth: 1,
    flex: 1,
    justifyContent: "center",
    padding: 20,
  },
  permissionText: {
    color: palette.text,
    fontSize: 14,
    lineHeight: 22,
    textAlign: "center",
  },
  iconButton: {
    alignItems: "center",
    borderColor: "transparent",
    borderRadius: 9999,
    borderWidth: 0,
    height: 44,
    justifyContent: "center",
    width: 44,
  },
  pdfModal: {
    backgroundColor: palette.background,
    flex: 1,
  },
  pdfHeader: {
    alignItems: "center",
    borderBottomColor: palette.border,
    borderBottomWidth: 1,
    flexDirection: "row",
    gap: 12,
    paddingBottom: 12,
    paddingHorizontal: 16,
    paddingTop: 54,
  },
  pdfTitle: {
    color: palette.text,
    fontSize: 16,
    fontWeight: "800",
  },
  pdfFrame: {
    flex: 1,
  },
  pdfWebView: {
    backgroundColor: palette.background,
    flex: 1,
  },
});
