import { StyleSheet } from "react-native";

export const palette = {
  background: "#0b0f14",
  surface: "#121820",
  surfaceRaised: "#18202a",
  border: "rgba(255,255,255,0.09)",
  borderStrong: "rgba(255,255,255,0.18)",
  text: "#f8fafc",
  muted: "#a8b3c1",
  subtle: "#738091",
  green: "#7dd3a6",
  greenSoft: "rgba(45,212,132,0.13)",
  blue: "#8cc7ff",
  blueSoft: "rgba(56,189,248,0.13)",
  amber: "#f7c873",
  amberSoft: "rgba(245,158,11,0.13)",
  red: "#fda4af",
  redSoft: "rgba(244,63,94,0.14)",
  ink: "#071018",
};

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: palette.background,
  },
  appShell: {
    flex: 1,
  },
  mainScroll: {
    flex: 1,
  },
  topBar: {
    paddingHorizontal: 20,
    paddingTop: 14,
    paddingBottom: 10,
  },
  brandRow: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 12,
  },
  brandCopy: {
    flex: 1,
    gap: 4,
  },
  eyebrow: {
    color: palette.subtle,
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 2.6,
    textTransform: "uppercase",
  },
  appTitle: {
    color: palette.text,
    fontSize: 28,
    fontWeight: "800",
  },
  appSubtitle: {
    color: palette.muted,
    fontSize: 14,
    lineHeight: 21,
    marginTop: 8,
  },
  connectionPill: {
    alignItems: "center",
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: "row",
    gap: 7,
    paddingHorizontal: 11,
    paddingVertical: 8,
  },
  connectionPillReady: {
    backgroundColor: palette.greenSoft,
    borderColor: "rgba(125,211,166,0.35)",
  },
  connectionPillWaiting: {
    backgroundColor: palette.amberSoft,
    borderColor: "rgba(247,200,115,0.35)",
  },
  pillDot: {
    borderRadius: 999,
    height: 8,
    width: 8,
  },
  pillDotReady: {
    backgroundColor: palette.green,
  },
  pillDotWaiting: {
    backgroundColor: palette.amber,
  },
  connectionPillText: {
    color: palette.text,
    fontSize: 12,
    fontWeight: "800",
  },
  scrollContent: {
    gap: 14,
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 24,
  },
  screen: {
    gap: 14,
  },
  heroPanel: {
    backgroundColor: palette.surface,
    borderColor: palette.border,
    borderRadius: 8,
    borderWidth: 1,
    gap: 14,
    padding: 16,
  },
  heroPanelReady: {
    backgroundColor: "#0f1b18",
    borderColor: "rgba(125,211,166,0.23)",
  },
  heroLabel: {
    color: palette.subtle,
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 2.2,
    textTransform: "uppercase",
  },
  heroTitle: {
    color: palette.text,
    fontSize: 24,
    fontWeight: "800",
    lineHeight: 30,
  },
  heroBody: {
    color: palette.muted,
    fontSize: 14,
    lineHeight: 22,
  },
  card: {
    backgroundColor: palette.surface,
    borderColor: palette.border,
    borderRadius: 8,
    borderWidth: 1,
    gap: 12,
    padding: 16,
  },
  cardRaised: {
    backgroundColor: palette.surfaceRaised,
  },
  cardTitle: {
    color: palette.text,
    fontSize: 18,
    fontWeight: "800",
    lineHeight: 23,
  },
  cardBody: {
    color: palette.muted,
    fontSize: 14,
    lineHeight: 22,
  },
  sectionHeader: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 12,
    paddingTop: 4,
  },
  sectionTitle: {
    color: palette.text,
    fontSize: 17,
    fontWeight: "800",
  },
  sectionKicker: {
    color: palette.subtle,
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 2,
    textTransform: "uppercase",
  },
  actionRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  primaryButton: {
    alignItems: "center",
    backgroundColor: palette.text,
    borderRadius: 8,
    justifyContent: "center",
    minHeight: 48,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  primaryButtonText: {
    color: palette.ink,
    fontSize: 14,
    fontWeight: "800",
  },
  secondaryButton: {
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.04)",
    borderColor: palette.borderStrong,
    borderRadius: 8,
    borderWidth: 1,
    justifyContent: "center",
    minHeight: 48,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  secondaryButtonText: {
    color: palette.text,
    fontSize: 14,
    fontWeight: "800",
  },
  pressed: {
    opacity: 0.78,
    transform: [{ scale: 0.99 }],
  },
  metricGrid: {
    flexDirection: "row",
    gap: 10,
  },
  metricCard: {
    flex: 1,
    backgroundColor: palette.surface,
    borderColor: palette.border,
    borderRadius: 8,
    borderWidth: 1,
    gap: 7,
    minHeight: 86,
    padding: 14,
  },
  metricLabel: {
    color: palette.subtle,
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 1.8,
    textTransform: "uppercase",
  },
  metricValue: {
    color: palette.text,
    fontSize: 24,
    fontWeight: "800",
  },
  metricHint: {
    color: palette.muted,
    fontSize: 12,
    lineHeight: 17,
  },
  listRow: {
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.035)",
    borderColor: palette.border,
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: "row",
    gap: 12,
    padding: 12,
  },
  listRowActive: {
    backgroundColor: palette.blueSoft,
    borderColor: "rgba(140,199,255,0.36)",
  },
  courseAvatar: {
    alignItems: "center",
    backgroundColor: "#223041",
    borderRadius: 8,
    height: 42,
    justifyContent: "center",
    width: 42,
  },
  courseAvatarText: {
    color: palette.blue,
    fontSize: 13,
    fontWeight: "900",
  },
  rowText: {
    flex: 1,
    gap: 3,
  },
  rowTitle: {
    color: palette.text,
    fontSize: 14,
    fontWeight: "800",
    lineHeight: 19,
  },
  rowSubtitle: {
    color: palette.muted,
    fontSize: 12,
    lineHeight: 17,
  },
  badge: {
    alignSelf: "flex-start",
    borderColor: palette.borderStrong,
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 9,
    paddingVertical: 5,
  },
  badgeText: {
    color: palette.muted,
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 1.2,
    textTransform: "uppercase",
  },
  input: {
    backgroundColor: "rgba(0,0,0,0.2)",
    borderColor: palette.border,
    borderRadius: 8,
    borderWidth: 1,
    color: palette.text,
    fontSize: 14,
    minHeight: 48,
    paddingHorizontal: 13,
    paddingVertical: 12,
  },
  emptyText: {
    color: palette.muted,
    fontSize: 14,
    lineHeight: 22,
  },
  statusBanner: {
    borderRadius: 8,
    borderWidth: 1,
    gap: 8,
    padding: 14,
  },
  statusBannerInfo: {
    backgroundColor: palette.blueSoft,
    borderColor: "rgba(140,199,255,0.28)",
  },
  statusBannerError: {
    backgroundColor: palette.redSoft,
    borderColor: "rgba(253,164,175,0.35)",
  },
  statusTitle: {
    color: palette.text,
    fontSize: 14,
    fontWeight: "800",
  },
  statusBody: {
    color: palette.muted,
    fontSize: 13,
    lineHeight: 19,
  },
  errorText: {
    color: palette.red,
    fontSize: 13,
    lineHeight: 19,
  },
  bottomNav: {
    backgroundColor: "rgba(11,15,20,0.96)",
    borderColor: palette.border,
    borderTopWidth: 1,
    flexDirection: "row",
    gap: 8,
    paddingBottom: 18,
    paddingHorizontal: 12,
    paddingTop: 10,
  },
  navItem: {
    alignItems: "center",
    borderRadius: 8,
    flex: 1,
    gap: 5,
    minHeight: 54,
    justifyContent: "center",
  },
  navItemActive: {
    backgroundColor: "rgba(255,255,255,0.08)",
  },
  navMarker: {
    backgroundColor: "transparent",
    borderRadius: 999,
    height: 3,
    width: 20,
  },
  navMarkerActive: {
    backgroundColor: palette.blue,
  },
  navLabel: {
    color: palette.subtle,
    fontSize: 11,
    fontWeight: "800",
  },
  navLabelActive: {
    color: palette.text,
  },
  sectionCard: {
    backgroundColor: "rgba(255,255,255,0.035)",
    borderColor: palette.border,
    borderRadius: 8,
    borderWidth: 1,
    gap: 10,
    padding: 13,
  },
  moduleRow: {
    alignItems: "flex-start",
    flexDirection: "row",
    gap: 10,
    paddingVertical: 3,
  },
  moduleRail: {
    backgroundColor: palette.blue,
    borderRadius: 999,
    height: 8,
    marginTop: 7,
    width: 8,
  },
  moduleLink: {
    color: palette.blue,
    fontSize: 12,
    lineHeight: 17,
  },
  modalSafeArea: {
    flex: 1,
    backgroundColor: palette.background,
    padding: 20,
    gap: 16,
  },
  modalHeader: {
    gap: 14,
  },
  modalTitle: {
    color: palette.text,
    fontSize: 27,
    fontWeight: "800",
  },
  modalBody: {
    color: palette.muted,
    fontSize: 14,
    lineHeight: 22,
  },
  modalCameraFrame: {
    backgroundColor: "#000",
    borderColor: palette.borderStrong,
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    overflow: "hidden",
    position: "relative",
  },
  camera: {
    flex: 1,
  },
  scanGuide: {
    aspectRatio: 1,
    borderColor: "rgba(248,250,252,0.9)",
    borderRadius: 8,
    borderWidth: 2,
    left: "15%",
    position: "absolute",
    top: "24%",
    width: "70%",
  },
  permissionBox: {
    alignItems: "center",
    backgroundColor: palette.surface,
    borderColor: palette.border,
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    justifyContent: "center",
    padding: 20,
  },
  permissionText: {
    color: palette.text,
    fontSize: 14,
    lineHeight: 22,
    textAlign: "center",
  },
});
