package cli

import (
	"fmt"
	"io"
	"os/exec"
	"runtime"
	"strings"

	"github.com/DotNaos/moodle-services/internal/moodle"
	"github.com/spf13/cobra"
)

const defaultDockerImage = "ghcr.io/dotnaos/moodle-services:latest"
const installDockerURL = "https://raw.githubusercontent.com/DotNaos/moodle-services/main/scripts/install-docker.sh"

var (
	bootstrapCopy       bool
	bootstrapPrint      bool
	bootstrapSchool     string
	bootstrapUsername   string
	bootstrapPassword   string
	bootstrapImage      string
	bootstrapApplyValue string
)

type bootstrapServerResult struct {
	Status               string `json:"status" yaml:"status"`
	Command              string `json:"command" yaml:"command"`
	Copied               bool   `json:"copied" yaml:"copied"`
	ReusedMobileSession  bool   `json:"reusedMobileSession" yaml:"reusedMobileSession"`
	MobileSessionPath    string `json:"mobileSessionPath" yaml:"mobileSessionPath"`
	SiteURL              string `json:"siteUrl" yaml:"siteUrl"`
	UserID               int    `json:"userId" yaml:"userId"`
	TokenRedacted        string `json:"tokenRedacted" yaml:"tokenRedacted"`
	PrivateTokenRedacted string `json:"privateTokenRedacted,omitempty" yaml:"privateTokenRedacted,omitempty"`
	SafetyNote           string `json:"safetyNote" yaml:"safetyNote"`
}

type bootstrapApplyResult struct {
	Status            string `json:"status" yaml:"status"`
	MobileSessionPath string `json:"mobileSessionPath" yaml:"mobileSessionPath"`
	SiteURL           string `json:"siteUrl" yaml:"siteUrl"`
	UserID            int    `json:"userId" yaml:"userId"`
	TokenRedacted     string `json:"tokenRedacted" yaml:"tokenRedacted"`
	Validated         bool   `json:"validated" yaml:"validated"`
}

var bootstrapCmd = &cobra.Command{
	Use:   "bootstrap",
	Short: "Create one-command server bootstrap payloads",
	Long:  "Create a Moodle mobile token locally and generate a one-command Docker install for a server.",
	ValidArgsFunction: func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return nil, cobra.ShellCompDirectiveNoFileComp
	},
	RunE: func(cmd *cobra.Command, args []string) error {
		return helpOrMachineError(cmd, "expected a bootstrap subcommand")
	},
}

var bootstrapServerCmd = &cobra.Command{
	Use:   "server",
	Short: "Create a server install command",
	Long:  "Create or reuse a Moodle mobile token, seal it into a bootstrap payload, and print or copy the server Docker install command.",
	Args:  cobra.NoArgs,
	ValidArgsFunction: func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return nil, cobra.ShellCompDirectiveNoFileComp
	},
	RunE: func(cmd *cobra.Command, args []string) error {
		result, err := runBootstrapServer()
		if err != nil {
			return err
		}
		return writeCommandOutput(cmd, result, func(w io.Writer) error {
			return renderBootstrapServerText(w, result)
		})
	},
}

var bootstrapApplyCmd = &cobra.Command{
	Use:    "apply",
	Short:  "Apply a bootstrap payload",
	Args:   cobra.NoArgs,
	Hidden: true,
	ValidArgsFunction: func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		return nil, cobra.ShellCompDirectiveNoFileComp
	},
	RunE: func(cmd *cobra.Command, args []string) error {
		result, err := runBootstrapApply(bootstrapApplyValue)
		if err != nil {
			return err
		}
		return writeCommandOutput(cmd, result, func(w io.Writer) error {
			return renderBootstrapApplyText(w, result)
		})
	},
}

func init() {
	markAPIOptional(bootstrapCmd)
	markAPIOptional(bootstrapServerCmd)
	markAPIOptional(bootstrapApplyCmd)

	bootstrapServerCmd.Flags().BoolVar(&bootstrapCopy, "copy", false, "Copy the server install command to the clipboard")
	bootstrapServerCmd.Flags().BoolVar(&bootstrapPrint, "print", false, "Print the server install command")
	bootstrapServerCmd.Flags().StringVar(&bootstrapSchool, "school", "", "School id override")
	bootstrapServerCmd.Flags().StringVar(&bootstrapUsername, "username", "", "Moodle username/email for one-time QR scraping")
	bootstrapServerCmd.Flags().StringVar(&bootstrapPassword, "password", "", "Moodle password for one-time QR scraping")
	bootstrapServerCmd.Flags().StringVar(&bootstrapImage, "image", defaultDockerImage, "Docker image used by the generated server command")
	bootstrapServerCmd.RegisterFlagCompletionFunc("school", completeSchoolIDs)

	bootstrapApplyCmd.Flags().StringVar(&bootstrapApplyValue, "payload", "", "Bootstrap payload generated by 'moodle bootstrap server'")

	bootstrapCmd.AddCommand(bootstrapServerCmd, bootstrapApplyCmd)
}

func runBootstrapServer() (bootstrapServerResult, error) {
	image := strings.TrimSpace(bootstrapImage)
	if image == "" {
		image = defaultDockerImage
	}

	session, reused, err := loadOrCreateBootstrapMobileSession()
	if err != nil {
		return bootstrapServerResult{}, err
	}
	if session.SchoolID == "" {
		session.SchoolID = moodle.ActiveSchoolID
	}

	payload, err := moodle.EncodeBootstrapPayload(moodle.NewBootstrapPayload(session, image))
	if err != nil {
		return bootstrapServerResult{}, err
	}
	command := buildServerInstallCommand(payload, image)

	copied := false
	if bootstrapCopy {
		if err := copyToClipboard(command); err != nil {
			return bootstrapServerResult{}, fmt.Errorf("copy install command: %w", err)
		}
		copied = true
	}

	result := bootstrapServerResult{
		Status:               "ready",
		Command:              command,
		Copied:               copied,
		ReusedMobileSession:  reused,
		MobileSessionPath:    opts.MobileSessionPath,
		SiteURL:              session.SiteURL,
		UserID:               session.UserID,
		TokenRedacted:        moodle.RedactSecret(session.Token),
		PrivateTokenRedacted: moodle.RedactSecret(session.PrivateToken),
		SafetyNote:           "The generated command contains a Moodle mobile token. Treat it like a password and do not share it.",
	}
	if !bootstrapPrint && bootstrapCopy && !isMachineOutput() {
		result.Command = ""
	}
	return result, nil
}

func loadOrCreateBootstrapMobileSession() (moodle.MobileSession, bool, error) {
	if session, err := moodle.LoadMobileSession(opts.MobileSessionPath); err == nil {
		client, clientErr := moodle.NewMobileClient(session, session.ResolvedSchoolID())
		if clientErr == nil && client.ValidateSession() == nil {
			return session, true, nil
		}
	}

	if bootstrapUsername != "" || bootstrapPassword != "" || bootstrapSchool != "" {
		school, username, password, err := resolveLoginInputs(bootstrapSchool, bootstrapUsername, bootstrapPassword)
		if err != nil {
			return moodle.MobileSession{}, false, err
		}
		if username == "" || password == "" {
			return moodle.MobileSession{}, false, fmt.Errorf("bootstrap server requires username and password when no reusable session exists")
		}
		if _, err := loginAndSaveSession(school, username, password); err != nil {
			return moodle.MobileSession{}, false, err
		}
	}

	client, err := ensureAuthenticatedClient()
	if err != nil {
		return moodle.MobileSession{}, false, err
	}
	link, err := client.FetchMobileQRLink()
	if err != nil {
		return moodle.MobileSession{}, false, err
	}
	token, err := client.ExchangeMobileQRToken(link)
	if err != nil {
		return moodle.MobileSession{}, false, err
	}
	session := moodle.MobileSessionFromToken(token)
	session.SchoolID = client.School.ID
	if err := moodle.SaveMobileSession(opts.MobileSessionPath, session); err != nil {
		return moodle.MobileSession{}, false, err
	}
	return session, false, nil
}

func runBootstrapApply(rawPayload string) (bootstrapApplyResult, error) {
	if strings.TrimSpace(rawPayload) == "" {
		return bootstrapApplyResult{}, fmt.Errorf("--payload is required")
	}
	payload, err := moodle.DecodeBootstrapPayload(rawPayload)
	if err != nil {
		return bootstrapApplyResult{}, err
	}
	session := payload.MobileSession
	if session.SchoolID == "" {
		session.SchoolID = moodle.ActiveSchoolID
	}

	client, err := moodle.NewMobileClient(session, session.ResolvedSchoolID())
	if err != nil {
		return bootstrapApplyResult{}, err
	}
	if err := client.ValidateSession(); err != nil {
		return bootstrapApplyResult{}, err
	}
	if err := moodle.SaveMobileSession(opts.MobileSessionPath, session); err != nil {
		return bootstrapApplyResult{}, err
	}

	return bootstrapApplyResult{
		Status:            "applied",
		MobileSessionPath: opts.MobileSessionPath,
		SiteURL:           session.SiteURL,
		UserID:            session.UserID,
		TokenRedacted:     moodle.RedactSecret(session.Token),
		Validated:         true,
	}, nil
}

func buildServerInstallCommand(payload string, image string) string {
	command := fmt.Sprintf("curl -fsSL %s | bash -s -- --payload '%s'", installDockerURL, payload)
	if strings.TrimSpace(image) != "" && image != defaultDockerImage {
		command += fmt.Sprintf(" --image '%s'", image)
	}
	return command
}

func copyToClipboard(text string) error {
	switch runtime.GOOS {
	case "darwin":
		return runClipboardCommand("pbcopy", text)
	case "linux":
		if err := runClipboardCommand("wl-copy", text); err == nil {
			return nil
		}
		return runClipboardCommand("xclip", text, "-selection", "clipboard")
	default:
		return fmt.Errorf("clipboard copy is not supported on %s; rerun with --print", runtime.GOOS)
	}
}

func runClipboardCommand(name string, input string, args ...string) error {
	cmd := exec.Command(name, args...)
	stdin, err := cmd.StdinPipe()
	if err != nil {
		return err
	}
	if err := cmd.Start(); err != nil {
		return err
	}
	if _, err := io.WriteString(stdin, input); err != nil {
		_ = stdin.Close()
		_ = cmd.Wait()
		return err
	}
	if err := stdin.Close(); err != nil {
		_ = cmd.Wait()
		return err
	}
	return cmd.Wait()
}

func renderBootstrapServerText(w io.Writer, result bootstrapServerResult) error {
	if _, err := fmt.Fprintf(w, "status: %s\n", result.Status); err != nil {
		return err
	}
	if _, err := fmt.Fprintf(w, "site: %s\n", result.SiteURL); err != nil {
		return err
	}
	if _, err := fmt.Fprintf(w, "user id: %d\n", result.UserID); err != nil {
		return err
	}
	if _, err := fmt.Fprintf(w, "mobile session: %s\n", result.MobileSessionPath); err != nil {
		return err
	}
	if _, err := fmt.Fprintf(w, "reused mobile session: %t\n", result.ReusedMobileSession); err != nil {
		return err
	}
	if result.Copied {
		if _, err := fmt.Fprintln(w, "server install command copied to clipboard"); err != nil {
			return err
		}
	}
	if result.Command != "" {
		if _, err := fmt.Fprintf(w, "\n%s\n", result.Command); err != nil {
			return err
		}
	}
	_, err := fmt.Fprintf(w, "note: %s\n", result.SafetyNote)
	return err
}

func renderBootstrapApplyText(w io.Writer, result bootstrapApplyResult) error {
	if _, err := fmt.Fprintf(w, "status: %s\n", result.Status); err != nil {
		return err
	}
	if _, err := fmt.Fprintf(w, "mobile session: %s\n", result.MobileSessionPath); err != nil {
		return err
	}
	if _, err := fmt.Fprintf(w, "site: %s\n", result.SiteURL); err != nil {
		return err
	}
	if _, err := fmt.Fprintf(w, "user id: %d\n", result.UserID); err != nil {
		return err
	}
	_, err := fmt.Fprintf(w, "validated: %t\n", result.Validated)
	return err
}
